// Code generated by MCHP Chatbot
#ifndef EPWM_H
#define EPWM_H

#include <xc.h>
#include <stdint.h>

// ---- PCPWM Default Bitfield Macros ----
// Code generated by MCHP Chatbot


void epwm_enable_interrupt(void);
void epwm_disable_interrupt(void);

// --- Advanced config struct ---
typedef struct {
    unsigned period;      // PTPERH/L
    uint16_t duty[4];     // PDC0/1/2/3[H/L]: Four pairs
    uint8_t deadtime;     // DTCON
    uint8_t override;     // OVDCOND
    uint8_t override_state; // OVDCONS
    uint8_t fault;        // FLTCONFIG
    uint8_t ptcon0, ptcon1;
    uint8_t pwmcon0, pwmcon1;
} epwm_advanced_cfg_t;

void epwm_init_advanced(const epwm_advanced_cfg_t* cfg);
void epwm_set_pair_duty(uint8_t pair, uint16_t duty);
void epwm_set_deadtime(uint8_t dtval);
void epwm_set_override(uint8_t ov_en_mask, uint8_t ov_state_mask);
void epwm_set_fault(uint8_t flt_cfgval);
void epwm_update_period(unsigned periodval);
void epwm_start(void);
void epwm_stop(void);
void epwm_set_isr(void (*cb)(void));
void epwm_isr_handler(void);

#endif // EPWM_H

