// Code generated by MCHP Chatbot
#ifndef EPWM_CONFIG_H
#define EPWM_CONFIG_H

// ---- PTCON0: Time Base Mode (PTMOD<1:0>, bits 1-0) ----
#define PCPWM_PTCON0_TB_FREERUN        (0b00) // Free Running mode
#define PCPWM_PTCON0_TB_SINGLESHOT     (0b01) // Single-Shot mode
#define PCPWM_PTCON0_TB_CONTUPDOWN     (0b10) // Continuous Up/Down mode
#define PCPWM_PTCON0_TB_CONTUPDOWNINT  (0b11) // Continuous Up/Down with Interrupt

// ---- PTCON0: PWM Time Base Input Clock Prescale Select (PTCKPS<1:0>, bits 3-2) ----
#define PCPWM_PTCON0_PRESCALE_1        (0b00 << 2) // 1:1 prescale
#define PCPWM_PTCON0_PRESCALE_4        (0b01 << 2) // 1:4 prescale
#define PCPWM_PTCON0_PRESCALE_16       (0b10 << 2) // 1:16 prescale
#define PCPWM_PTCON0_PRESCALE_64       (0b11 << 2) // 1:64 prescale

// ---- PTCON0: Output Postscale (PTOPS<3:0>, bits 7-4) ----
#define PCPWM_PTCON0_POSTSCALE_1       (0b0000 << 4) // 1:1 postscale
#define PCPWM_PTCON0_POSTSCALE_2       (0b0001 << 4)
#define PCPWM_PTCON0_POSTSCALE_3       (0b0010 << 4)
#define PCPWM_PTCON0_POSTSCALE_4       (0b0011 << 4)
#define PCPWM_PTCON0_POSTSCALE_5       (0b0100 << 4)
#define PCPWM_PTCON0_POSTSCALE_6       (0b0101 << 4)
#define PCPWM_PTCON0_POSTSCALE_7       (0b0110 << 4)
#define PCPWM_PTCON0_POSTSCALE_8       (0b0111 << 4)
#define PCPWM_PTCON0_POSTSCALE_9       (0b1000 << 4)
#define PCPWM_PTCON0_POSTSCALE_10      (0b1001 << 4)
#define PCPWM_PTCON0_POSTSCALE_11      (0b1010 << 4)
#define PCPWM_PTCON0_POSTSCALE_12      (0b1011 << 4)
#define PCPWM_PTCON0_POSTSCALE_13      (0b1100 << 4)
#define PCPWM_PTCON0_POSTSCALE_14      (0b1101 << 4)
#define PCPWM_PTCON0_POSTSCALE_15      (0b1110 << 4)
#define PCPWM_PTCON0_POSTSCALE_16      (0b1111 << 4)

// ---- PTCON1: PWM Timer Enable/Direction (bits 7: enable, 6: direction) ----
#define PCPWM_PTCON1_ENABLE            (0x80)
#define PCPWM_PTCON1_DISABLE           (0x00)
#define PCPWM_PTCON1_FWD               (0x00) // Forward (count up)
#define PCPWM_PTCON1_REV               (0x40) // Reverse (count down)
// ---- DTCON: Dead-Time Control (lower 6 bits) ----
#define PCPWM_DTCON_DEADTIME(d)        ((uint8_t)((d) & 0x3F)) // Sets dead-time value (0-63)

// ---- PWMCON0: Output Pair Modes and Enables ----
// Each bit enables or sets mode for each PWM pair
#define PCPWM_PWMCON0_PAIR1_COMPLEMENTARY   (1<<0) // Pair 1 complementary mode
#define PCPWM_PWMCON0_PAIR2_COMPLEMENTARY   (1<<1) // Pair 2 complementary mode
#define PCPWM_PWMCON0_PAIR3_COMPLEMENTARY   (1<<2) // Pair 3 complementary mode
#define PCPWM_PWMCON0_PAIR4_COMPLEMENTARY   (1<<3) // Pair 4 complementary mode

#define PCPWM_PWMCON0_PAIR1_INDEP           (0<<0) // Pair 1 independent mode
#define PCPWM_PWMCON0_PAIR2_INDEP           (0<<1)
#define PCPWM_PWMCON0_PAIR3_INDEP           (0<<2)
#define PCPWM_PWMCON0_PAIR4_INDEP           (0<<3)
#define PCPWM_PWMCON0_ALLPAIR_COMPLEMENTARY   (PCPWM_PWMCON0_PAIR1_COMPLEMENTARY|\
    PCPWM_PWMCON0_PAIR2_COMPLEMENTARY|\
    PCPWM_PWMCON0_PAIR4_COMPLEMENTARY|\
    PCPWM_PWMCON0_PAIR4_COMPLEMENTARY)

// ---- PWMCON0:  PWM Module Enable bits ----
#define PCPWM_PWMCON0_PWMEN_ALL_ODD     (0b111<<4) // All odd PWM I/O pins are enabled for PWM output
#define PCPWM_PWMCON0_PWMEN_1_AND_3     (0b110<<4) // PWM1, PWM3 pins enabled
#define PCPWM_PWMCON0_PWMEN_ALL         (0b101<<4) // All PWM I/O pins enabled
#define PCPWM_PWMCON0_PWMEN_0_TO_5      (0b100<<4) // PWM0, PWM1, PWM2, PWM3, PWM4, PWM5 enabled

// ---- DTCON: Dead-Time Control (lower 6 bits) ----
// DTPS<1:0> bits (Dead-Time Prescale Select):
#define PCPWM_DTCON_DTPS_2      (0b00 << 6) // FOSC/2
#define PCPWM_DTCON_DTPS_4      (0b01 << 6) // FOSC/4
#define PCPWM_DTCON_DTPS_8      (0b10 << 6) // FOSC/8
#define PCPWM_DTCON_DTPS_16     (0b11 << 6) // FOSC/16
// DEAD TIME value (lower 6 bits)
#define PCPWM_DTCON_DEADTIME(val)   ((uint8_t)((val) & 0x3F))
// Combine prescaler and dead-time value for DTCON (DTPS + DTA)
#define PCPWM_DTCON_BUILD(dtps, dta) ((dtps) | ((dta) & 0x3F))
#define PCPWM_PWMCON0_PWMEN_0_TO_3      (0b011<<4) // PWM0, PWM1, PWM2, PWM3 enabled
#define PCPWM_PWMCON0_PWMEN_0_AND_1     (0b010<<4) // PWM0 and PWM1 enabled
#define PCPWM_PWMCON0_PWMEN_1_ONLY      (0b001<<4) // Only PWM1 enabled
#define PCPWM_PWMCON0_PWMEN_DISABLED    (0b000<<4) // PWM module disabled; all PWM I/O become GPIO

// ---- OVERRIDE & FAULT Default Macros ----
#define PCPWM_OVDCOND_DEFAULT     0x00    // No override, all output drivers controlled by PWM
#define PCPWM_OVDCONS_DEFAULT     0x00    // No override state, all output states low
#define PCPWM_FLTCONFIG_DEFAULT   0x00    // No fault inputs enabled, default

// ---- PWMCON1: Synchronization and Special Event ----
#define PCPWM_PWMCON1_NO_SYNC       (0x00) // No sync
#define PCPWM_PWMCON1_OSYNC         (1<<0) // Override sync
#define PCPWM_PWMCON1_UDIS          (1<<1) // Update disable
#define PCPWM_PWMCON1_SEVTDIR       (1<<3) // Special event direction
#define PCPWM_PWMCON1_SEVOPS(n)     (((n)&0xF)<<4) // Special event output postscaler value [n=0-15]


#endif // EPWM_CONFIG_H

