// Code generated by MCHP Chatbot
#include "epwm.h"

// --- POWER CONTROL PWM MODULE ONLY (PIC18F4431) ---
static void (*epwm_user_callback)(void) = 0;

// Code generated by MCHP Chatbot
void epwm_init_advanced(const epwm_advanced_cfg_t* cfg) {
    PTCON0 = cfg->ptcon0;
    PTCON1 = cfg->ptcon1;
    PWMCON0 = cfg->pwmcon0;
    PWMCON1 = cfg->pwmcon1;
    PTMRL = 0; PTMRH = 0;
    PTPERL = (uint8_t)(cfg->period & 0xFF);
    PTPERH = (uint8_t)((cfg->period >> 8) & 0xFF);
    PDC0L = (uint8_t)(cfg->duty[0] & 0xFF); PDC0H = (uint8_t)((cfg->duty[0] >> 8) & 0xFF);
    PDC1L = (uint8_t)(cfg->duty[1] & 0xFF); PDC1H = (uint8_t)((cfg->duty[1] >> 8) & 0xFF);
    PDC2L = (uint8_t)(cfg->duty[2] & 0xFF); PDC2H = (uint8_t)((cfg->duty[2] >> 8) & 0xFF);
    PDC3L = (uint8_t)(cfg->duty[3] & 0xFF); PDC3H = (uint8_t)((cfg->duty[3] >> 8) & 0xFF);
    DTCON = cfg->deadtime;    // Now: full DTCON value including prescale and dead-time bits
    OVDCOND = cfg->override;
    OVDCONS = cfg->override_state;
    FLTCONFIG = cfg->fault;
// Set output pins to digital outputs
    TRISB =0xf;
    TRISC =0b11000110;
    /* ANSELH = 0; */ // Not present on all 18F4431 variants
}

void epwm_enable_interrupt(void) {
    PIR3bits.PTIF = 0;    // Clear PTIF interrupt flag
    PIE3bits.PTIE = 1;    // Enable PWM interrupt
    INTCONbits.PEIE = 1;  // Enable peripheral interrupts
    INTCONbits.GIE = 1;   // Enable all interrupts
}

void epwm_disable_interrupt(void) {
    PIE3bits.PTIE = 0;    // Disable PWM interrupt
    // You may optionally clear flags and global enables if desired
}
    

void epwm_set_pair_duty(uint8_t pair, uint16_t duty) {
    switch(pair) {
    case 0: PDC0L = duty & 0xFF; PDC0H = (duty >> 8) & 0xFF; break;
    case 1: PDC1L = duty & 0xFF; PDC1H = (duty >> 8) & 0xFF; break;
    case 2: PDC2L = duty & 0xFF; PDC2H = (duty >> 8) & 0xFF; break;
    case 3: PDC3L = duty & 0xFF; PDC3H = (duty >> 8) & 0xFF; break;
    default: break;
    }
}

void epwm_set_deadtime(uint8_t dtval) { DTCON = dtval & 0x3F; }
void epwm_set_override(uint8_t ov_en_mask, uint8_t ov_state_mask) { OVDCOND = ov_en_mask; OVDCONS = ov_state_mask; }
void epwm_set_fault(uint8_t flt_cfgval) { FLTCONFIG = flt_cfgval; }
void epwm_update_period(unsigned periodval) { PTPERL = periodval & 0xFF; PTPERH = (periodval >> 8) & 0xFF; }

// Change: PTCON0 (PWM enable bit) must be set/cleared bitwise, not as a bitfield
void epwm_start(void)  { PTCON0 |= 0x80; }  // PTEN = 1
void epwm_stop(void)   { PTCON0 &= ~0x80; } // PTEN = 0

// --- ISR logic ---
// Code generated by MCHP Chatbot
void epwm_set_isr(void (*cb)(void)) { epwm_user_callback = cb; }
void epwm_isr_handler(void) {
    // Use correct Power Control PWM interrupt bits (PIR3bits.PTIF, PIE3bits.PTIE)
    if (PIR3bits.PTIF && PIE3bits.PTIE) {
        if (epwm_user_callback) epwm_user_callback();
        PIR3bits.PTIF = 0;
    }
}


