// Code generated by MCHP Chatbot
#include "libraries/pwm/epwm.h"
#include "libraries/pwm/epwm_config.h"
#include <math.h>
#include <stdint.h>
#define _XTAL_FREQ 10e6
#define SINE_FREQ   400
#define PWM_FREQ    20000
#define LUT_SIZE    (PWM_FREQ/SINE_FREQ)
#define MAX_DUTY    1500

uint16_t sine_LUT[LUT_SIZE];
volatile uint8_t sample_idx = 0;

void setup_sine_LUT(void) {
    for (int i = 0; i < LUT_SIZE; i++) {
        double angle = (2.0 * 3.1415926536 * i) / LUT_SIZE;
        sine_LUT[i] = (uint16_t)((0.5 + 0.4 * sin(angle)) * MAX_DUTY);
    }
}

void pwm_update_callback(void) {
    uint8_t idx_a = sample_idx;
    uint8_t idx_b = (sample_idx + LUT_SIZE / 3) % LUT_SIZE;
    uint8_t idx_c = (sample_idx + 2 * LUT_SIZE / 3) % LUT_SIZE;
    //OVDCOND = idx_a==(LUT_SIZE-1)? 1<<8:1<<7;
    epwm_set_pair_duty(0, sine_LUT[idx_a]);
    epwm_set_pair_duty(1, sine_LUT[idx_b]);
    epwm_set_pair_duty(2, sine_LUT[idx_c]);
    epwm_set_pair_duty(3, 120); // 4th pair not used

    sample_idx = (sample_idx + 1) % LUT_SIZE;
}



int main(void) {
    setup_sine_LUT();
    epwm_advanced_cfg_t cfg = {
        .period          = 499,
        .duty            = {0,0,0,0},
        // Set DTCON to use dead-time prescale (FOSC/8) and dead-time value (e.g. 16):
        .deadtime        = PCPWM_DTCON_BUILD(PCPWM_DTCON_DTPS_2, 8),
        .override        = 0xFF,
        .override_state  = 0x00,
        .fault           = 0x00,
        .ptcon0          = (PCPWM_PTCON0_TB_FREERUN|PCPWM_PTCON0_PRESCALE_1 | PCPWM_PTCON0_POSTSCALE_1),
        .ptcon1          = (PCPWM_PTCON1_ENABLE | PCPWM_PTCON1_FWD),
        .pwmcon0         = (PCPWM_PWMCON0_ALLPAIR_COMPLEMENTARY|PCPWM_PWMCON0_PWMEN_ALL),
        .pwmcon1         = (PCPWM_PWMCON1_NO_SYNC)//|PCPWM_PWMCON1_UDIS)
    };
    epwm_init_advanced(&cfg);
    epwm_set_isr(pwm_update_callback);
    epwm_start();
    epwm_enable_interrupt();

    while (1) {
        // All logic in ISR
        //epwm_set_override(255, 0);
    }
    return 0;
}

